apiVersion: apps/v1
kind: Deployment
metadata: 
  name: contact-be-deployment
  namespace: ok-pta-qa-modules
spec: 
  selector: 
    matchLabels: 
      app: contact-be-container
  template: 
    metadata: 
      labels: 
        app: contact-be-container
    spec:
      initContainers:              
        - name: init-db
          image: postgres:9.6.22-alpine3.14
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_DB_ROLE
              value: cbd_service
            - name: APP_DBNAME
              value: ContactBaseDataQa  
            - name: PGHOST
              value: postgresql-svc.ok-pta-shared.svc.cluster.local
            - name: PGUSER 
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_DB_PASSWORD
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_DB_PASSWORD       
          command:
          - /bin/sh
          - -c
          - >
            echo Waiting for DB to be ready...;
            while ! pg_isready >dev/null; do sleep 3; done;
            echo DB is ready and accepting conncetions;
            sleep 3;
            echo Creating database ${APP_DBNAME} if not exists;
            psql -tc "SELECT 1 FROM pg_database WHERE datname = '${APP_DBNAME}'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE \"${APP_DBNAME}\"";          
            echo Creating role ${APP_DB_ROLE} if not exists;
            psql -tc "SELECT 1 FROM pg_user WHERE usename = '${APP_DB_ROLE}'" | grep -q 1 || psql -c "CREATE USER \"${APP_DB_ROLE}\"";
            echo Job finished;        
        - name: schema-migration
          image: registry.gitlab.com/openkonsequenz/qa/contactbasedata-backend:1.0.0-flyway
          imagePullPolicy: IfNotPresent
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgresql-svc.ok-pta-shared.svc.cluster.local:5432/ContactBaseDataQa
            - name: FLYWAY_USER
              value: postgres
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_DB_PASSWORD          
          command: ["flyway", "info" ,"migrate", "info"]
      containers: 
        - image: "registry.gitlab.com/openkonsequenz/qa/contactbasedata-backend:develop"
          name: contact-be-container
          env:
            - name: SPRING_CONFIG_LOCATION
              value: 'file:/config/'
            - name: POSTGRES_DB_USER
              valueFrom: 
                secretKeyRef: 
                  key: POSTGRES_DB_USER
                  name: postgresql-secrets
            - name: POSTGRES_DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: POSTGRES_DB_PASSWORD
                  name: postgresql-secrets
            - name: POSTGRES_SERVICE
              value: postgresql-svc.ok-pta-shared
            - name: POSTGRES_DB_NAME
              value: ContactBaseDataQa
            - name: POSTGRES_HOST
              value: postgresql-svc.ok-pta-shared.svc.cluster.local
          ports:
            - containerPort: 9155
          volumeMounts:
            - name: config-volume
              mountPath: /config/              
              readOnly: true      
      volumes:
        - name: config-volume
          configMap:
            name: contact-be-config
            items:
            - key: application.yml
              path: application_localdev.yml
---
apiVersion: v1
kind: Service
metadata:
  name: contact-be-service
  namespace: ok-pta-qa-modules
spec:
  selector:
    app: contact-be-container
  ports:
    - protocol: TCP
      port: 9155
      targetPort: 9155
