apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: ok-pta-dev-modules

images:
  - name: "registry.gitlab.com/openkonsequenz/qa/contactbasedata-frontend"
    newName: "registry.gitlab.com/openkonsequenz/dev/contactbasedata-frontend"
    newTag: "latest"

configMapGenerator:
  - name: contact-fe-config
    files:
      - configs/development.json