
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ok-pta-dev-modules

bases:
  - ../../base

images:
  - name: "registry.gitlab.com/openkonsequenz/qa/contactbasedata-backend:develop"
    newName: "registry.gitlab.com/openkonsequenz/dev/contactbasedata-backend:develop"
    newTag: "latest"

patchesStrategicMerge:  
  - contact-be-deployment.yaml
configMapGenerator:
  - name: contact-be-config        
    files:
      - configs/application.yml