apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ok-pta-qa-modules

bases:
  - ../../base

#patchesStrategicMerge:
#  - contact-be-deployment.yaml

configMapGenerator:
  - name: contact-be-config    
    files:
      - configs/application.yml