{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
  annotations:
    #argocd.argoproj.io/hook: {{ .syncHook | default "Sync" | quote }}
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}  
spec:
  destination:
    namespace: {{ .destNamespace }}
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
{{- end }}