apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contactbasedata-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ok-pta-qa-modules
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: contactbasedata-backend/environments/qa/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
