apiVersion: apps/v1
kind: Deployment
metadata: 
  name: contact-fe-deployment
  namespace: ok-pta-qa-modules
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: contact-fe-container
  template: 
    metadata: 
      labels: 
        app: contact-fe-container
    spec: 
      containers: 
        - 
          image: "registry.gitlab.com/openkonsequenz/qa/contactbasedata-frontend:latest"
          name: contact-fe-container
          ports: 
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config/development.json
              subPath: development.json
              readOnly: true      
      volumes:
        - name: config-volume
          configMap:
            name: contact-fe-config
            items:
            - key: development.json
              path: development.json
---
apiVersion: v1
kind: Service
metadata:
  name: contact-fe-service
  namespace: ok-pta-qa-modules
spec:
  selector:
    app: contact-fe-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
 