apiVersion: v1
data:
  POSTGRES_DB_PASSWORD: dGVzNkFldjg=
  POSTGRES_DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:  
  name: postgresql-secrets
  namespace: ok-pta-qa-modules
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
data:
  POSTGRES_DB_PASSWORD: dGVzNkFldjg=
  POSTGRES_DB_USER: cG9zdGdyZXM=
kind: Secret
metadata:  
  name: postgresql-secrets
  namespace: ok-pta-shared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
