namespaces:
  - name: ok-pta-qa-modules
  - name: ok-pta-shared
  - name: traefik
apps:
  - name: init
    destNamespace: default
    path: shared/
  - name: contactbasedata-backend
    destNamespace: ok-pta-qa-modules
    path: apps/contactbasedata/contactbasedata-backend/environments/qa/
  # - name: contactbasedata-backend
  #   destNamespace: ok-pta-qa-modules
  #   path: contactbasedata-backend/environments/dev/
  - name: contactbasedata-frontend
    destNamespace: ok-pta-qa-modules
    path: apps/contactbasedata/contactbasedata-frontend/environments/qa/

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/SourceTrees/argocd1
    targetRevision: HEAD