bases:
  - ../../base
patches:
  #- contact-be-configmap.yaml
  - contactbackend.yaml
configMapGenerator:
  - name: contact-be-config
    namespace: ok-pta-qa-modules
    #behavior: replace
    files:
      - configs/application.yml