apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: ok-pta-dev-modules

images:
  - name: registry.gitlab.com/openkonsequenz/qa/contactbasedata-frontend:latest
    newName: registry.gitlab.com/openkonsequenz/dev/contactbasedata-frontend:latest

configMapGenerator:
  - name: portal-config
    files:
      - configs/backendConfig.json
      - configs/moduleConfig.json